### PR TITLE
Fix for various bugs and issues

### PR DESCRIPTION
**Pull request by german-one**
For a detailed description see #2 

Obsoletes: #1 
Closes: #2

### CODE REVIEW

**Comment by bitcrazed** [comment]
Many thanks for your thoughtful improvements :)

**Comment by german-one** [comment]
I planned to contribute to the terminal project but was not familiar with GitHub yet. So, I was looking for a training object in order to exercise how forks, commits, PR's, and stuff actually work. And I found one. Sorry for picking yours and stealing your time ... couldn't resist 😉

Steffen

**Comment by german-one** [comment]
FWIW What ever you merged here differs from my commit and will not even compile.

**Comment by bitcrazed** [comment]
LOL :) No problem. This was just a quick little tool I knocked up <strike>in</strike> between meetings - meant to stabilize and improve it somewhat, and when I returned to the project I found you'd already done some of the work ;)

> FWIW, for small repos like this, no need to write a detailed multi-bug report AND a PR - just a bug or two for the over-arching issues and then the meat in the PR should be pretty self-evident 😉 

There may have been a merge conflict w.r.t. `DisplayUsage()`. Making a few more adjustments and will push an update later today.

**Pull request merged**
